#!/bin/bash
# Check for parameters: IP and gateway addresses
ip=192.168.1.15
gw=192.168.1.254

# Create ifcfg-eth1 file
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth1
DEVICE=eth1
NAME="eth1"
TYPE=Ethernet
BOOTPROTO=static
IPADDR=$ip
NETMASK=255.255.255.0
GATEWAY=$2
DNS1="8.8.8.8"
ONBOOT=yes
NM_CONTROLLED=no
IPV4_FAILURE_FATAL="no"
DEFROUTE="yes"
IPV6INIT="no"
EOF

ifup eth1
