#!/bin/bash
# Check for parameters: version, ip, mask and gateway addresses
if [[ $# != 4 ]]; then
    echo ""
    echo "  Usage: prom-install <version> <ip-addr> <mask> <gateway>"
    echo ""
    echo "      version: the Prometheus version to install. see https://prometheus.io/download"
    echo "      ip-addr, mask and gateway: the ip address info to be assigned to the bridged NIC"
    echo "      'mask' is in x.x.x.x form, e.g. 255.255.255.0"
    echo ""
    exit 1
fi

prometheus_version=$1
bridged_nic_ipaddr=$2
bridged_nic_subnet_mask=$3
bridged_nic_default_gateway=$4
clean_install="true"

# Text color
red=$'\e[1;31m'
grn=$'\e[1;32m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
wht=$'\e[1;0m'


# Check that eth1 exists
ifconfig eth1 > /dev/null 2>&1
if [[ $? != 0 ]]; then
    echo "${red}[!]    ${wht}Interface 'eth1' does NOT exist!"
    echo ""
    exit 1
fi
# Create ifcfg-eth1 file
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth1
DEVICE=eth1
NAME="eth1"
TYPE=Ethernet
BOOTPROTO=static
IPADDR=$bridged_nic_ipaddr
NETMASK=$bridged_nic_subnet_mask
GATEWAY=$bridged_nic_default_gateway
DNS1="8.8.8.8"
ONBOOT=yes
NM_CONTROLLED=no
IPV4_FAILURE_FATAL="no"
DEFROUTE="yes"
IPV6INIT="no"
EOF

ifup eth1 2> /dev/null
# Check eth1 is up and running
if [[ $(ifconfig eth1 2> /dev/null | grep RUNNING| wc -l) != 1 ]]; then
    echo "${red}[!]    ${wht}Interface 'eth1' is NOT up and running"
    clean_install="false"
fi

# Download and extract Prometheus package
cd /tmp
wget https://github.com/prometheus/prometheus/releases/download/v${prometheus_version}/prometheus-${prometheus_version}.linux-amd64.tar.gz
if [[ $? != 0 ]]; then
    echo "${red}[!]    ${wht}Failed to download the Prometheus package!"
    echo ""
    clean_install="false"
    exit 2
fi
tar -xvf prometheus-${prometheus_version}.linux-amd64.tar.gz
if [[ $? != 0 ]]; then
    echo "${red}[!]    ${wht}Failed to unzip the Prometheus package!"
    echo ""
    clean_install="false"
    exit 3
fi

# Create Prometheus User
useradd --no-create-home --shell /bin/false prometheus

# create directories
mkdir /etc/prometheus
mkdir /var/lib/prometheus

# Move files to proper locations
cd /tmp/prometheus-${prometheus_version}.linux-amd64  
mv console* /etc/prometheus/
mv prometheus.yml /etc/prometheus/
mv prometheus promtool /usr/local/bin/

# Set directoy and file owner:group
chown -R prometheus:prometheus /etc/prometheus/
chown prometheus:prometheus /var/lib/prometheus
chown prometheus:prometheus /usr/local/bin/prometheus
chown prometheus:prometheus /usr/local/bin/promtool

# Create service file
cat <<EOF > /etc/systemd/system/prometheus.service
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
    --config.file /etc/prometheus/prometheus.yml \
    --storage.tsdb.path /var/lib/prometheus/ \
    --web.console.templates=/etc/prometheus/consoles \
    --web.console.libraries=/etc/prometheus/console_libraries

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable prometheus
systemctl start prometheus

echo ""
echo ""
if [[ $clean_install == "true" ]]; then
    echo "${grn}[ok]    ${wht}Installation complete!"
else
    echo "${mag}[?]    ${wht}Installation complete! Please review any errors."
fi
echo "        Run ${cyn}'prom-checks'${wht} to verifiy installation"
echo ""
echo ""

