#!/bin/bash
# prom-install

# Text color
red=$'\e[1;31m'
grn=$'\e[1;32m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
wht=$'\e[1;0m'

# Check for parameters: version:w
if [[ $# != 1 ]]; then
    echo ""
    echo "  Usage: prom-install <version>"
    echo ""
    echo "      version: the Prometheus version to install. see https://prometheus.io/download"
    echo "      11/16/2019: Current version - ${cyn}2.14.0${wht}"
    echo ""
    exit 1
fi

prometheus_version=$1
clean_install="true"


# Download and extract Prometheus package
cd /tmp
wget https://github.com/prometheus/prometheus/releases/download/v${prometheus_version}/prometheus-${prometheus_version}.linux-amd64.tar.gz
if [[ $? != 0 ]]; then
    echo "${red}[!]    ${wht}Failed to download the Prometheus package!"
    echo ""
    clean_install="false"
    exit 2
fi
tar -xvf prometheus-${prometheus_version}.linux-amd64.tar.gz
if [[ $? != 0 ]]; then
    echo "${red}[!]    ${wht}Failed to unzip the Prometheus package!"
    echo ""
    clean_install="false"
    exit 3
fi

# Create Prometheus User
useradd --no-create-home --shell /bin/false prometheus

# create directories
mkdir /etc/prometheus
mkdir /var/lib/prometheus

# Move files to proper locations
cd /tmp/prometheus-${prometheus_version}.linux-amd64  
mv console* /etc/prometheus/
mv prometheus.yml /etc/prometheus/
mv prometheus promtool /usr/local/bin/

# Set directoy and file owner:group
chown -R prometheus:prometheus /etc/prometheus/
chown prometheus:prometheus /var/lib/prometheus
chown prometheus:prometheus /usr/local/bin/prometheus
chown prometheus:prometheus /usr/local/bin/promtool

# Create service file
cat <<EOF > /etc/systemd/system/prometheus.service
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
    --config.file /etc/prometheus/prometheus.yml \
    --storage.tsdb.path /var/lib/prometheus/ \
    --web.console.templates=/etc/prometheus/consoles \
    --web.console.libraries=/etc/prometheus/console_libraries

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable prometheus
systemctl start prometheus

echo ""
echo ""
if [[ $clean_install == "true" ]]; then
    echo "${grn}[ok]    ${wht}Installation complete!"
else
    echo "${mag}[?]    ${wht}Installation complete! Please review any errors."
fi
echo "        Run ${cyn}'prom-checks'${wht} to verifiy installation"
echo ""
echo ""

