#!/bin/bash
## File: prom-checks

# Text color
red=$'\e[1;31m'
grn=$'\e[1;32m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
wht=$'\e[1;0m'

prometheus_version=2.13.1

# Config eth1
echo "${wht}Check bridged NIC:"
if [[ -e /etc/sysconfig/network-scripts/ifcfg-eth1 ]]; then
    echo "${grn}ifcfg-eth1 exists"
else
    echo "${red}ifcfg-eth1 does NOT exist"
fi
if [[ $(ifconfig eth1 | grep RUNNING| wc -l) == 1 ]]; then
    echo "${grn}eth1 interface up and running"
else
    echo "${red}eth1 interface NOT up and running"
fi

# Download package
echo ""
echo "${wht}Check prometheus package downloaded and extracted:"
if [[ -d /tmp/prometheus-${prometheus_version}.linux-amd64 ]]; then
    echo "${grn}Prometheus package downloaded and extracted"
else
    echo "${red}Prometheus package NOT downloaded and extracted"
fi

# create Prometheus user
echo ""
echo "${wht}Check prometheus user created:"
if id prometheus > /dev/null 2>&1; then
    echo "${grn}'prometheus' user exists"
else
    echo "${red}'prometheus' user does NOT exist"
fi


# prometheus service files
prometheus_dirs=(/etc/prometheus /etc/prometheus/consoles /etc/prometheus/console_libraries /var/lib/prometheus)
prometheus_files=(/etc/prometheus/prometheus.yml /usr/local/bin/prometheus /usr/local/bin/promtool)

echo ""
echo "${wht}Check directory owner:group:"
for d in ${prometheus_dirs[@]}; do
    if [[ -d $d ]] && 
       [[ $(stat -c %U $d) == "prometheus" ]] &&
       [[ $(ls -ld $d | awk '{print $4}') == "prometheus" ]]; then
         echo "${grn}$d  Goot"
    else
         echo "${red}$d  NOT goot"
    fi
done

echo ""
echo "${wht}Check file owner:group:"
for f in ${prometheus_files[@]}; do
    if [[ -f $f ]] &&
       [[ $(stat -c %U $f) == "prometheus" ]] &&
       [[ $(ls -l $f | awk '{print $4}') == "prometheus" ]]; then
         echo "${grn}$f  Goot"
    else
         echo "${red}$f  NOT goot"
    fi
done

echo ""
echo "${wht}Check executable files:"
for f in ${prometheus_files[@]}; do
    if [[ -x $f ]]; then
         echo "${grn}$f  executable"
    else
         if [[ $f == "/etc/prometheus/prometheus.yml" ]]; then continue; fi
         echo "${red}$f  NOT executable"
    fi
done


echo ""
echo ""



echo "${wht}"

