#!/bin/bash
## File: prom-uninstall

prometheus_version=2.13.1


ifdown eth1
rm /etc/sysconfig/network-scripts/ifcfg-eth1

rm -rf /tmp/prometheus*

userdel prometheus

rm -rf /etc/prometheus
rm -rf /var/lib/prometheus

rm /usr/local/bin/prometheus
rm /usr/local/bin/promtool
